name: Generate Kodi Playlist

on:
  schedule:
    - cron: "0 */11 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Generate Playlist
        run: |
          JSON_URL="https://pkll.xojiv79335.workers.dev/"
          OUTPUT="playlist.m3u"

          echo "#EXTM3U" > $OUTPUT

          curl -s "$JSON_URL" > data.json

          while IFS= read -r name; do
          
            jq -r --arg name "$name" '
            .[] | select(.channel_name==$name) |
            "#EXTINF:-1 tvg-id=\"" + .channel_id +
            "\" group-title=\"" + .channel_genre +
            "\" tvg-logo=\"" + .channel_logo +
            "\"," + .channel_name + "\n" +

            "#KODIPROP:inputstream=inputstream.adaptive\n" +

            "#KODIPROP:inputstream.adaptive.drm={\"org.w3.clearkey\":{\"license\":{\"keyids\":{\"" +
            .keyId + "\":\"" + .key + "\"}}}}\n" +

            "#KODIPROP:inputstream.adaptive.common_headers=User-Agent=plaYtv/7.1.3 (Linux;Android 13) ygx/69.1 ExoPlayerLib/824.0&Cookie=" +
            .cookie + "\n" +

            .channel_url + "\n"
            ' data.json >> $OUTPUT

          done < channels.txt

      - name: Commit Playlist
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add playlist.m3u

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Auto update Kodi playlist"
            git push
          fi
