name: Generate Kodi Playlist

on:
  schedule:
    - cron: "0 */11 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Generate Playlist
        run: |
          JSON_URL="https://pkll.xojiv79335.workers.dev/"
          OUTPUT="playlist.m3u"

          echo -e '#EXTM3U url-tvg="https://avkb.short.gy/jioepg.xml.gz"\n' > $OUTPUT

          curl -s "$JSON_URL" > data.json

          jq -r --rawfile ch channels.txt '
          def wanted: ($ch[0] | split("\n") | map(select(length>0)));

          .[] | select(.channel_name as $n | wanted | index($n)) |

          (.channel_url | split("?")[0] | endswith(".mpd")) as $isdash |
          (.channel_url | split("?")[0] | endswith(".m3u8")) as $ishls |

          "#EXTINF:-1 tvg-id=\"" + .channel_id +
          "\" group-title=\"" + .channel_genre +
          "\" tvg-logo=\"" + .channel_logo +
          "\"," + .channel_name + "\n" +

          "#KODIPROP:contentlookup=False\n" +

          (if $isdash then
          "#KODIPROP:mimetype=application/dash+xml\n"
          elif $ishls then
          "#KODIPROP:mimetype=application/vnd.apple.mpegurl\n"
          else "" end) +

          "#KODIPROP:inputstream=inputstream.adaptive\n" +

          (if $isdash then
          "#KODIPROP:inputstream.adaptive.drm={\"org.w3.clearkey\":{\"license\":{\"keyids\":{\"" +
          .keyId + "\":\"" + .key + "\"}}}}\n"
          else "" end) +

          "#KODIPROP:inputstream.adaptive.common_headers=User-Agent=plaYtv/7.1.3 (Linux;Android 13) ygx/69.1 ExoPlayerLib/824.0&Cookie=" +
          .cookie + "\n" +

          .channel_url + "\n"
          ' data.json >> $OUTPUT

      - name: Commit Playlist
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add playlist.m3u
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "update playlist.m3u"
            git push
          fi
